### PR TITLE
Add rev-del to README

### PR DESCRIPTION
**Pull request by callumacrae**
I can add a code sample if you want it: figure this is probably the best place for it, though.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'd rather have a succinct description of what it does after the link.

**Comment by callumacrae** [comment]
Done!

**Comment by bobthecow** [comment]
would be nice to have such a description for the other ones, too :)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-rev/commit/80d40efbfd5de355b9b21fd9df28e0eba25c4197

**Pull request closed without merging**
