### PR TITLE
Add option to mutate the key created in manifest file

### PR DESCRIPTION
**Pull request by robguy21**
### What's new?
Options can now accept a `keyModifier` property which is a function that changes the key that is saved in the manifest file

### CODE REVIEW

**Comment by sindresorhus** [comment]
What's the use-case? What problem does it solve?

**Comment by robguy21** [comment]
@sindresorhus my use case was the following:

In Laravel, the native blade template function `mix()` will prepend a `/` when it searches for entries in the manifest file.

For example:
```
# template.blade.php
mix('style.css') // searches for a "/style.css" entry in the manifest
```

So the easiest path for me was to just modify the key's that gulp-rev outputs to include a `/` -

```
      keyModifier(name) {
        return `/${name}`;
      },
```

I'd rather not PR a change to the Laravel mix function since that is a much larger library with a lot more complexity and interdependencies (rabbit holes) that I'd prefer not to go down.

**Comment by sindresorhus** [comment]
> I'd rather not PR a change to the Laravel mix function since that is a much larger library with a lot more complexity and interdependencies (rabbit holes) that I'd prefer not to go down.

I understand, but I'm also not very interested in adding more complexity here.

**Comment by sindresorhus** [comment]
You might be able to solve this with the `transformer` option.

**Pull request closed without merging**
