### PR TITLE
Adds support for rails4 manifest files

### PR DESCRIPTION
**Pull request by itsthatguy**
It's all in the title

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sorry. Out of scope of this plugin. Create a new one. This one is feature complete.

**Comment by bobthecow** [comment]
The Gulp Way is to use a lot of small, specialized plugins instead of a few configurable plugins.

For this, it'd make a lot of sense to split it off into a `gulp-rev-rails4-manifest` plugin which you could use in conjunction with `gulp-rev`, instead of (or beside) the `rev.manifest` version.

**Comment by itsthatguy** [comment]
sounds good.

**Comment by bobthecow** [comment]
And be sure to open a PR to add it to the ["Works with gulp-rev"](https://github.com/sindresorhus/gulp-rev#works-with-gulp-rev) section of the README :)

**Pull request closed without merging**
