### PR TITLE
allow the hash function to be overwritten

### PR DESCRIPTION
**Pull request by jondejong**
Allowing a custom hash function to be passed in via a new options parameter.

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. Please look at existing issues. This has already been declined multiple times. I'm not interested in bloating this plugin with unnecessary things.

**Comment by bobthecow** [comment]
We could bloat the plugin with a comment just above the line that calls md5 letting people know not to open a PR :)

**Comment by aaronzirbes** [comment]
I've been waiting for this. Please re-open and merge. It's not bloat. There is a reason you have seen multiple pull requests for this feature. Because it's very very useful.

**Comment by tjsail33** [comment]
I've been watching this issue, but what is the usefulness of a custom hash function? Are you seeing issues were the hash isn't unique after a change? I don't see a use case, so I don't see a reason for this either and agree with the collaborators.

**Comment by aaronzirbes** [comment]
Anyone who wants to maintain a high volume production site hosted via S3 and wants to be able to rollback a git commit based on the commit SHA rather than individual file MD5 hashes that are entirely unrelated to the commit. . It's a very useful rollback features.

**Comment by tjsail33** [comment]
you could upload the generated manifest to S3 including the MD5 hashes to S3, and name that with your git commit SHA? That way the hashes are recoverable?

**Comment by johnrengelman** [comment]
The use case is a from a devops perspective. The files are intricately connected because they are built together. Allowing a custom hash function allows all the deployable files to be named with a common unique identifier for that particular build. This can simplify deployments and rollbacks in multiple environments because they can be tied to a VCS version.

**Comment by bobthecow** [comment]
If you're just trying to use a common unique identifier (like git rev) that sounds a lot like a different plugin entirely. [gulp-rename](https://github.com/hparra/gulp-rename) maybe?

**Comment by johnrengelman** [comment]
At the cost of the support of downstream plugins that rely on the output of gulp-rev.

**Comment by shinygang** [comment]
I use  [gulp-rev-replace](https://github.com/jamesknelson/gulp-rev-replace)  to replace the link

**Comment by danveloper** [comment]
What is the status on this PR. I'd really like this feature. Should I fork the plugin? Is anybody else maintaining a fork with this change??

**Pull request closed without merging**
